<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>WallWalker</AssemblyName>
    <RootNamespace>WallWalker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bonelab.GameLibs.Steam" Version="6.0.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
